### ISSUE TITLE
Is this repo licensed under MIT?

### ISSUE THREAD

**Issue by leejuyuu** [yiwen-ai/xid-ts#6]
Hello, I could not find a license file in this repository, and the license section in the readme seems to be copied from another repo so the link is dead. Was the package intended to be licensed under MIT?

**Comment by zensh** [comment]
Sorry, just added, https://github.com/yiwen-ai/xid-ts/blob/main/LICENSE

**Comment by leejuyuu** [comment]
Thanks a lot!
